Dev magda apply UI
Wunderbyte-GmbH/moodle-local_catquiz pull request #159
Opened 2023-10-02 10:44 UTC by eynimeni

thank you!

2023-10-02 11:22 UTC, davidszkiba requested changes
Mir sind nur ein paar Kleinigkeiten aufgefallen, aber sonst schaut's gut aus :+1:

2023-10-02 11:22 UTC, davidszkiba commented on templates/catscalemanagers.mustache
> +            <!--a href="{{link}}"-->
Kann man wahrscheinlich entfernen, oder?

2023-10-02 11:22 UTC, davidszkiba commented on templates/catscalemanagers.mustache
> +            <!--/a-->
Das kann man wohl auch entfernen?

2023-10-02 11:22 UTC, davidszkiba commented on templates/catscalechildren.mustache
> +        "viewlink":"http://localhost:8000/local/catquiz/manage_catscales.php?id=3#lcq_questions"
Das betrifft nicht direkt deine Änderung, aber: funktioniert der viewlink so auch auf anderen Hosts und Ports? Kann man http://HOSTNAME:port/ vielleicht einfach weglassen, damit immer der aktuelle Hostname und Port verwendet wird? Also funktioniert es auch als `"viewlink":"/local/catquiz/manage...."`?

2023-10-02 11:22 UTC, davidszkiba commented on lang/de/local_catquiz.php
> +// Validation
Kommentare sollten mit einem Punkt enden :detective:

2023-10-02 11:22 UTC, davidszkiba commented on db/events.php
> +    array(
Ich denke wir sollten ab jetzt die short array Syntax mit den eckigen Klammern verwenden

2023-10-02 11:22 UTC, davidszkiba commented on classes/output/catscaledashboard.php
> +        /*     // TODO: Check if this is needed somewhere
Kann das entfernt werden? Evtl einfach nach dem String im ganzen Projekt suchen um sicherzugehen, dass es nirgends verwendet wird?

2023-10-02 11:22 UTC, davidszkiba commented on classes/observer.php
> +     * Observer for the testitem_imported event
Ich glaub solche Kommentare sollen auch mit einem Punkt enden, oder?

2023-10-03 08:43 UTC, eynimeni commented on templates/catscalechildren.mustache
> +        "viewlink":"http://localhost:8000/local/catquiz/manage_catscales.php?id=3#lcq_questions"
das ist eh nur der beispielhafte link, deswegen ist es in diesem fall egal

2023-10-03 08:54 UTC, merged