Update model_raschmodel.php
Wunderbyte-GmbH/moodle-local_catquiz pull request #90
Opened 2023-08-01 19:31 UTC by ralferlebach

Added DIC, AIC, BIC, CAIC, AICc und saBIC

Propose deletion of deprecated function

2023-08-02 06:04 UTC, ralferlebach commented
Please check pramaters and data structure. I do not fully understand the data structures and architecture, so expect glitches to be fixed first.

This resolves #75

2023-08-03 08:10 UTC, davidszkiba requested changes
Danke für den Pull Request!

Mir sind ein paar Kleinigkeiten aufgefallen, die du bitte noch anpassen müsstest. Eigentlich sind es nur folgende Sachen:

- Die Funktion zum Filtern heißt `array_filter()`
- Der Verweis auf die `calc_DIC_item()` Methode benötigt ein `$this->`
- In PHP ist das kleiner-gleich Symbol `<=` statt `=<`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        foreach (arrayfilter($person_ability, function($var){return is_float($var);}, ARRAY_FILTER_USE_KEY) as $key => $pp)
Die Funktion heißt `array_filter` (mit Unterstricht). Im Moment führt das zu einem Fehler.
Optional kannst du auch den zweiten Parameter etwas verkürzen:
Statt `function($var){return is_float($var);}` kann man es mit Pfeilfunktionen auch so schreiben:
`fn ($var) => is_float($var)`
Siehe https://www.php.net/manual/de/functions.arrow.php

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        return $number_of_parameters * log($number_of_cases) + calc_DIC_item($model, $person_ability, $k);
Hier muss mit `$this->calc_DIC_item` auf die Funktion verwiesen werden, sonst wird sie nicht gefunden

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        $number_of_cases = count(arrayfilter($person_ability, function($var){return is_float($var);}, ARRAY_FILTER_USE_KEY));
`array_filter` statt `arrayfilter`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        return $number_of_parameters * (log($number_of_cases + 1)) + calc_DIC_item($model, $person_ability, $k);
Verweis mittels `$this->calc_DIC_item`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        $number_of_cases = count(arrayfilter($person_ability, function($var){return is_float($var);}, ARRAY_FILTER_USE_KEY));
`array_filter`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        return return 2 * $number_of_parameters + (2 * $number_of_parameters * ($number_of_parameters +1)) / ($number_of_cases - $number_of_parameters - 1) + calc_DIC_item($model, $person_ability, $k
`$this->calc_DIC_item`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        if ($number_of_cases - $number_of_parameters - 1 =< 0) return 0;
Kleiner-gleich ist in PHP `<=` :)

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        $number_of_cases = count(arrayfilter($person_ability, function($var){return is_float($var);}, ARRAY_FILTER_USE_KEY));
`array_filter`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        if ($number_of_cases - $number_of_parameters - 1 =< 0) return 0;
`<=`

2023-08-03 08:10 UTC, davidszkiba commented on classes/local/model/model_raschmodel.php
> +        return $number_of_parameters * log(($number_of_cases + 2) / 24) + calc_DIC_item($model, $person_ability, $k);
`$this->calc_DIC_item`

2023-08-07 06:31 UTC, ralferlebach commented on classes/local/model/model_raschmodel.php
> +    Wird diese Funktion noch irgendwo aufgerufen? */
Das muss natürlich geändert werden. Auf der Oberfläche soll schließlich die Likelihood der jeweiligen Modelle zu sehen sein.

2023-08-10 03:18 UTC, ralferlebach commented
Ist von @davidszkiba erledigt.

2023-08-10 03:18 UTC, closed without merging